sudo: false

dist: xenial

language: python

matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"
    - python: "3.10-dev"
  allow_failures:
    - python: "3.10-dev"

cache:
  pip: true

#env:
#  global:

#before_install:
#  -

install:
  - make

script:
  - make test-travis

#after_success: make coveralls