[tool.black]
line-length=79
exclude = '''
/(
    \.eggs/
  | \.git/
  | \.tox/
  | \.venv/
  | _build/
  | build/
  | dist/
  | venv/
)
'''

[build-system]
requires = [
    'setuptools>=40.8.0',
    'wheel',
]