# Generated by listennotes/devtools/api-sdks/sync.py python. Do not edit.


class ApiMethods:
    def search(self, **kwargs):
        return self._request_api(
            "GET",
            "/search",
            (
                "q",
                "sort_by_date",
                "type",
                "offset",
                "len_min",
                "len_max",
                "episode_count_min",
                "episode_count_max",
                "update_freq_min",
                "update_freq_max",
                "genre_ids",
                "published_before",
                "published_after",
                "only_in",
                "language",
                "region",
                "ocid",
                "ncid",
                "safe_mode",
                "unique_podcasts",
                "interviews_only",
                "sponsored_only",
                "page_size",
            ),
            kwargs,
        )

    def typeahead(self, **kwargs):
        return self._request_api(
            "GET",
            "/typeahead",
            ("q", "show_podcasts", "show_genres", "safe_mode"),
            kwargs,
        )

    def search_episode_titles(self, **kwargs):
        return self._request_api(
            "GET",
            "/search_episode_titles",
            ("q", "podcast_id", "podcast_id_type"),
            kwargs,
        )

    def spellcheck(self, **kwargs):
        return self._request_api(
            "GET",
            "/spellcheck",
            ("q",),
            kwargs,
        )

    def fetch_related_searches(self, **kwargs):
        return self._request_api(
            "GET",
            "/related_searches",
            ("q",),
            kwargs,
        )

    def fetch_trending_searches(self, **kwargs):
        return self._request_api(
            "GET",
            "/trending_searches",
            (),
            kwargs,
        )

    def fetch_best_podcasts(self, **kwargs):
        return self._request_api(
            "GET",
            "/best_podcasts",
            (
                "genre_id",
                "page",
                "region",
                "publisher_region",
                "language",
                "sort",
                "safe_mode",
            ),
            kwargs,
        )

    def fetch_podcast_by_id(self, **kwargs):
        return self._request_api(
            "GET",
            "/podcasts/{id}",
            ("next_episode_pub_date", "sort"),
            kwargs,
        )

    def delete_podcast(self, **kwargs):
        return self._request_api(
            "DELETE",
            "/podcasts/{id}",
            ("reason",),
            kwargs,
        )

    def fetch_episode_by_id(self, **kwargs):
        return self._request_api(
            "GET",
            "/episodes/{id}",
            ("show_transcript",),
            kwargs,
        )

    def batch_fetch_episodes(self, **kwargs):
        return self._request_api(
            "POST",
            "/episodes",
            (),
            kwargs,
        )

    def batch_fetch_podcasts(self, **kwargs):
        return self._request_api(
            "POST",
            "/podcasts",
            (),
            kwargs,
        )

    def fetch_curated_podcasts_list_by_id(self, **kwargs):
        return self._request_api(
            "GET",
            "/curated_podcasts/{id}",
            (),
            kwargs,
        )

    def fetch_podcast_genres(self, **kwargs):
        return self._request_api(
            "GET",
            "/genres",
            ("top_level_only",),
            kwargs,
        )

    def fetch_podcast_regions(self, **kwargs):
        return self._request_api(
            "GET",
            "/regions",
            (),
            kwargs,
        )

    def fetch_podcast_languages(self, **kwargs):
        return self._request_api(
            "GET",
            "/languages",
            (),
            kwargs,
        )

    def just_listen(self, **kwargs):
        return self._request_api(
            "GET",
            "/just_listen",
            (),
            kwargs,
        )

    def fetch_curated_podcasts_lists(self, **kwargs):
        return self._request_api(
            "GET",
            "/curated_podcasts",
            ("page",),
            kwargs,
        )

    def fetch_recommendations_for_podcast(self, **kwargs):
        return self._request_api(
            "GET",
            "/podcasts/{id}/recommendations",
            ("safe_mode",),
            kwargs,
        )

    def fetch_recommendations_for_episode(self, **kwargs):
        return self._request_api(
            "GET",
            "/episodes/{id}/recommendations",
            ("safe_mode",),
            kwargs,
        )

    def submit_podcast(self, **kwargs):
        return self._request_api(
            "POST",
            "/podcasts/submit",
            (),
            kwargs,
        )

    def fetch_playlist_by_id(self, **kwargs):
        return self._request_api(
            "GET",
            "/playlists/{id}",
            ("type", "last_timestamp_ms", "sort"),
            kwargs,
        )

    def fetch_my_playlists(self, **kwargs):
        return self._request_api(
            "GET",
            "/playlists",
            ("sort", "page"),
            kwargs,
        )

    def fetch_audience_for_podcast(self, **kwargs):
        return self._request_api(
            "GET",
            "/podcasts/{id}/audience",
            (),
            kwargs,
        )

    def fetch_podcasts_by_domain(self, **kwargs):
        return self._request_api(
            "GET",
            "/podcasts/domains/{domain_name}",
            ("page",),
            kwargs,
        )

    def create_playlist(self, **kwargs):
        return self._request_api(
            "POST",
            "/playlists",
            (),
            kwargs,
        )

    def update_playlist(self, **kwargs):
        return self._request_api(
            "PUT",
            "/playlists/{id}",
            (),
            kwargs,
        )

    def delete_playlist(self, **kwargs):
        return self._request_api(
            "DELETE",
            "/playlists/{id}",
            (),
            kwargs,
        )

    def add_playlist_item(self, **kwargs):
        return self._request_api(
            "POST",
            "/playlists/{id}/items",
            (),
            kwargs,
        )

    def delete_playlist_item(self, **kwargs):
        return self._request_api(
            "DELETE",
            "/playlists/{id}/items/{item_id}",
            (),
            kwargs,
        )

    def update_playlist_item_notes(self, **kwargs):
        return self._request_api(
            "PUT",
            "/playlists/{id}/items/{item_id}",
            (),
            kwargs,
        )
