name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.5, 3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Use Python ${{ matrix.node-version }}
      uses: actions/setup-python@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: make
    - run: make test-travis
